name: CD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Compile contract
        run: |
          wget https://legacy.smartpy.io/smartpy
          chmod a+x smartpy
          mkdir -p out
          ./smartpy compile contract.py ./out/

      - name: Install tezos cli
        run: |
          wget https://github.com/serokell/tezos-packaging/releases/latest/download/tezos-client
          chmod +x tezos-client
          mkdir -p $HOME/.local/bin
          mv tezos-client $HOME/.local/bin
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc