name: CD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      # - uses: docker-practice/actions-setup-docker@master
      #   timeout-minutes: 12

      - name: Install
        run: |
          bash install.sh --yes


      - name: Compile contract
        run: |
          ~/smartpy-cli/SmartPy.sh compile contract.py ./out/

      # - name: Deploy contract
      #   run: |



