name: Octo Organization CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Run a one-line script
        run: |
          wget https://legacy.smartpy.io/smartpy
          chmod a+x smartpy
          mkdir -p out
          ./smartpy compile contract.py ./out/


